name: Ubuntu build


on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Install packages
              run: |
                sudo apt-get install -y build-essential qtbase5-dev qt5-qmake qtchooser || sudo apt list

            - name: Clone repo
              uses: actions/checkout@v2
              with:
                ref: ${{ github.event.client_payload.branch }}

            - name: Get short sha1
              id: short_sha1
              run: echo "::set-output name=value::$(git rev-parse --short HEAD)"
              
            - name: Compile Lectronizer
              run: |
                qmake VER_SHA1=${{ steps.short_sha1.outputs.value }} lectronizer.pro
                make -j
                mkdir output
                cp lectronizer output

            - name: Upload package artifact
              uses: actions/upload-artifact@v1
              with:
                path: output
                name: lectronizer-${{ steps.short_sha1.outputs.value }}-ubuntu
                
